require('init_packer')
require('core/options')
require('core/keymaps')
require('plugins/fzf')
require('plugins/nerd_tree')
require('plugins/git_signs')
require('plugins/lsp')
require('plugins/async_tasks')
